/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import player.Jugador;

/**
 *
 * @author Luis Pottozen
 */
public class TicTacToe extends javax.swing.JFrame {

    String turno = "X";
    String siguienteTurno = "O";
    Jugador usuario1;
    Jugador usuario2;
    String jugador1 = "";
    String jugador2 = "";
    String score1;
    String score2;
    JLabel jlb[] = new JLabel[9];
    int vs[][] = {
        {1, 2, 3},
        {4, 5, 6},
        {7, 8, 9},
        {1, 4, 7},
        {2, 5, 8},
        {3, 6, 9},
        {1, 5, 9},
        {3, 5, 7},};

    public TicTacToe() {
        initComponents();
        iniciarJuego();
        this.setLocationRelativeTo(null);
        jlb[0] = casilla_1;
        jlb[1] = casilla_2;
        jlb[2] = casilla_3;
        jlb[3] = casilla_4;
        jlb[4] = casilla_5;
        jlb[5] = casilla_6;
        jlb[6] = casilla_7;
        jlb[7] = casilla_8;
        jlb[8] = casilla_9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        casilla_2 = new javax.swing.JLabel();
        casilla_3 = new javax.swing.JLabel();
        casilla_4 = new javax.swing.JLabel();
        casilla_5 = new javax.swing.JLabel();
        casilla_6 = new javax.swing.JLabel();
        casilla_1 = new javax.swing.JLabel();
        casilla_8 = new javax.swing.JLabel();
        casilla_9 = new javax.swing.JLabel();
        casilla_7 = new javax.swing.JLabel();
        jlWelcome = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JLPlayer1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLPlayer2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLScore1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JLScore2 = new javax.swing.JLabel();
        btnReiniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(55, 58, 64));
        jPanel2.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(104, 109, 118));

        casilla_2.setBackground(new java.awt.Color(238, 238, 238));
        casilla_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        casilla_2.setForeground(new java.awt.Color(33, 33, 33));
        casilla_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla_2.setOpaque(true);
        casilla_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                casilla_2MousePressed(evt);
            }
        });

        casilla_3.setBackground(new java.awt.Color(238, 238, 238));
        casilla_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        casilla_3.setForeground(new java.awt.Color(33, 33, 33));
        casilla_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla_3.setOpaque(true);
        casilla_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                casilla_3MousePressed(evt);
            }
        });

        casilla_4.setBackground(new java.awt.Color(238, 238, 238));
        casilla_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        casilla_4.setForeground(new java.awt.Color(33, 33, 33));
        casilla_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla_4.setOpaque(true);
        casilla_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                casilla_4MousePressed(evt);
            }
        });

        casilla_5.setBackground(new java.awt.Color(238, 238, 238));
        casilla_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        casilla_5.setForeground(new java.awt.Color(33, 33, 33));
        casilla_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla_5.setOpaque(true);
        casilla_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                casilla_5MousePressed(evt);
            }
        });

        casilla_6.setBackground(new java.awt.Color(238, 238, 238));
        casilla_6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        casilla_6.setForeground(new java.awt.Color(33, 33, 33));
        casilla_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla_6.setOpaque(true);
        casilla_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                casilla_6MousePressed(evt);
            }
        });

        casilla_1.setBackground(new java.awt.Color(238, 238, 238));
        casilla_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        casilla_1.setForeground(new java.awt.Color(33, 33, 33));
        casilla_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla_1.setOpaque(true);
        casilla_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                casilla_1MousePressed(evt);
            }
        });

        casilla_8.setBackground(new java.awt.Color(238, 238, 238));
        casilla_8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        casilla_8.setForeground(new java.awt.Color(33, 33, 33));
        casilla_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla_8.setOpaque(true);
        casilla_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                casilla_8MousePressed(evt);
            }
        });

        casilla_9.setBackground(new java.awt.Color(238, 238, 238));
        casilla_9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        casilla_9.setForeground(new java.awt.Color(33, 33, 33));
        casilla_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla_9.setOpaque(true);
        casilla_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                casilla_9MousePressed(evt);
            }
        });

        casilla_7.setBackground(new java.awt.Color(238, 238, 238));
        casilla_7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        casilla_7.setForeground(new java.awt.Color(33, 33, 33));
        casilla_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla_7.setOpaque(true);
        casilla_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                casilla_7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(casilla_1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casilla_2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casilla_3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(casilla_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casilla_5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casilla_6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(casilla_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casilla_8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casilla_9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla_3, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(casilla_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casilla_4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casilla_8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jlWelcome.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jlWelcome.setForeground(new java.awt.Color(238, 238, 238));
        jlWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlWelcome.setText("Welcome to Tic Tac Toe");

        btnLimpiar.setBackground(new java.awt.Color(255, 51, 51));
        btnLimpiar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnIniciar.setBackground(new java.awt.Color(167, 255, 131));
        btnIniciar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnIniciar.setText("Salir");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Player 1:");

        JLPlayer1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        JLPlayer1.setForeground(new java.awt.Color(238, 238, 238));

        jLabel3.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Player 2:");

        JLPlayer2.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        JLPlayer2.setForeground(new java.awt.Color(238, 238, 238));

        jLabel2.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Score:");

        JLScore1.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        JLScore1.setForeground(new java.awt.Color(238, 238, 238));

        jLabel4.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("Score:");

        JLScore2.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        JLScore2.setForeground(new java.awt.Color(238, 238, 238));

        btnReiniciarJuego.setBackground(new java.awt.Color(0, 102, 255));
        btnReiniciarJuego.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnReiniciarJuego.setText("Reiniciar");
        btnReiniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(JLScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(JLScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(btnReiniciarJuego, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                                    .addComponent(btnIniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(0, 42, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLPlayer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JLPlayer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlWelcome)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReiniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JLScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JLScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -9, 580, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casilla_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_2MousePressed
        Presionar(2);
    }//GEN-LAST:event_casilla_2MousePressed

    private void casilla_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_3MousePressed
        Presionar(3);
    }//GEN-LAST:event_casilla_3MousePressed

    private void casilla_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_4MousePressed
        Presionar(4);
    }//GEN-LAST:event_casilla_4MousePressed

    private void casilla_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_5MousePressed
        Presionar(5);
    }//GEN-LAST:event_casilla_5MousePressed

    private void casilla_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_6MousePressed
        Presionar(6);
    }//GEN-LAST:event_casilla_6MousePressed

    private void casilla_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_1MousePressed
        Presionar(1);
    }//GEN-LAST:event_casilla_1MousePressed

    private void casilla_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_8MousePressed
        Presionar(8);
    }//GEN-LAST:event_casilla_8MousePressed

    private void casilla_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_9MousePressed
        Presionar(9);
    }//GEN-LAST:event_casilla_9MousePressed

    private void casilla_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_7MousePressed
        Presionar(7);
    }//GEN-LAST:event_casilla_7MousePressed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        for (int i = 0; i < jlb.length; i++) {
            jlb[i].setText("");
            jlb[i].setBackground(new Color(238, 238, 238));
        }

        turno = siguienteTurno;
        if (siguienteTurno.equals("O")) {
            siguienteTurno = "X";
        } else {
            siguienteTurno = "O";
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        JOptionPane.showMessageDialog(null, "Gracias... Vuelva Pronto");
        System.exit(0);

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnReiniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarJuegoActionPerformed
        iniciarJuego();
        for (int i = 0; i < jlb.length; i++) {
            jlb[i].setText("");
            jlb[i].setBackground(new Color(238, 238, 238));
        }
        
    }//GEN-LAST:event_btnReiniciarJuegoActionPerformed

    public void Presionar(int casilla) {
        if (jlb[casilla - 1].getText().equals("")) {
            jlb[casilla - 1].setText(turno);
            CambiarTurno();
            comprobarGanador();
        }
    }

    public void CambiarTurno() {
        if (turno.equals("X")) {
            turno = "O";
        } else {
            turno = "X";
        }
    }

    public void comprobarGanador() {
        for (int i = 0; i < vs.length; i++) {
            if (jlb[vs[i][0] - 1].getText().equals("X")
                    && jlb[vs[i][1] - 1].getText().equals("X")
                    && jlb[vs[i][2] - 1].getText().equals("X")) {

                jlb[vs[i][0] - 1].setBackground(Color.red);
                jlb[vs[i][1] - 1].setBackground(Color.red);
                jlb[vs[i][2] - 1].setBackground(Color.red);

                usuario1.acumularRecord();
                JOptionPane.showMessageDialog(null, "Gano " + usuario1.toString());
                JLScore1.setText(Integer.toString(usuario1.getRecord()));
                


            }
            if (jlb[vs[i][0] - 1].getText().equals("O")
                    && jlb[vs[i][1] - 1].getText().equals("O")
                    && jlb[vs[i][2] - 1].getText().equals("O")) {

                jlb[vs[i][0] - 1].setBackground(Color.red);
                jlb[vs[i][1] - 1].setBackground(Color.red);
                jlb[vs[i][2] - 1].setBackground(Color.red);
                
                usuario2.acumularRecord();
                JOptionPane.showMessageDialog(null, "Gano " + usuario2.toString());
                JLScore2.setText(Integer.toString(usuario2.getRecord()));
                
            }

        }
    }

    public void iniciarJuego() {
        jugador1 = JOptionPane.showInputDialog(null, "Ingrese Nombre del Primer Jugador");
        jugador2 = JOptionPane.showInputDialog(null, "Ingrese Nombre del Segundo Jugador");

        usuario1 = new Jugador(this.jugador1);
        usuario2 = new Jugador(this.jugador2);

        JLPlayer1.setText(usuario1.getNombre());
        JLPlayer2.setText(usuario2.getNombre());

        score1 = String.valueOf(usuario1.getRecord());
        score2 = String.valueOf(usuario1.getRecord());

        JLScore1.setText(this.score1);
        JLScore2.setText(this.score2);
    }

//    public void desactivado(){
//        btnReiniciar.setEnabled(false);
//    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLPlayer1;
    private javax.swing.JLabel JLPlayer2;
    private javax.swing.JLabel JLScore1;
    private javax.swing.JLabel JLScore2;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnReiniciarJuego;
    private javax.swing.JLabel casilla_1;
    private javax.swing.JLabel casilla_2;
    private javax.swing.JLabel casilla_3;
    private javax.swing.JLabel casilla_4;
    private javax.swing.JLabel casilla_5;
    private javax.swing.JLabel casilla_6;
    private javax.swing.JLabel casilla_7;
    private javax.swing.JLabel casilla_8;
    private javax.swing.JLabel casilla_9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlWelcome;
    // End of variables declaration//GEN-END:variables
}
